package com.zholtikov.cloud_dove.model;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import lombok.experimental.FieldDefaults;

import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@FieldDefaults(level = AccessLevel.PRIVATE)
public class PictureMeta {
    @Schema(name = "id", example = "123", description = "User ID, generated by the DataBase")
    Long id;

    @Schema(example = "33", description = "ID of the user, who uploaded this picture")
    Long ownerId;

    @Schema(example = "funny_cat.png", description = "File name")
    String fileName;

    @Schema(example = "2409030", description = "File size in bytes")
    Long fileSize;

    @Schema(example = "2024-11-09 12:14:28", description = "Date and time, when the picture was uploaded")
    LocalDateTime uploaded;
}
